/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.diegoacosta127.handicapp;
import javax.swing.*;

/**
 *
 * @author diegoacosta127
 */
public class JFrame_Main extends JFrame {

    DatabaseQuery app = new DatabaseQuery();
    /**
     * Creates new form JFrame_Main
     */
    public JFrame_Main() {
        initComponents();
        setTitle("Handicapp");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        export = new javax.swing.JMenu();
        export_season = new javax.swing.JMenuItem();
        export_team = new javax.swing.JMenuItem();
        export_player = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        edit_team = new javax.swing.JMenuItem();
        edit_player = new javax.swing.JMenuItem();
        edit_season = new javax.swing.JMenuItem();
        edit_country = new javax.swing.JMenuItem();
        menu_add = new javax.swing.JMenu();
        add_team = new javax.swing.JMenuItem();
        add_player = new javax.swing.JMenuItem();
        add_season = new javax.swing.JMenuItem();
        add_match = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        menu_file.setText("File");

        export.setText("Export");

        export_season.setText("Season");
        export_season.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_seasonActionPerformed(evt);
            }
        });
        export.add(export_season);

        export_team.setText("Team");
        export_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_teamActionPerformed(evt);
            }
        });
        export.add(export_team);

        export_player.setText("Player");
        export_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_playerActionPerformed(evt);
            }
        });
        export.add(export_player);

        menu_file.add(export);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        menu_file.add(exit);

        jMenuBar1.add(menu_file);

        menu_edit.setText("Edit");

        edit_team.setText("Team");
        edit_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_teamActionPerformed(evt);
            }
        });
        menu_edit.add(edit_team);

        edit_player.setText("Player");
        edit_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_playerActionPerformed(evt);
            }
        });
        menu_edit.add(edit_player);

        edit_season.setText("Season");
        edit_season.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_seasonActionPerformed(evt);
            }
        });
        menu_edit.add(edit_season);

        edit_country.setText("Country");
        edit_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_countryActionPerformed(evt);
            }
        });
        menu_edit.add(edit_country);

        jMenuBar1.add(menu_edit);

        menu_add.setText("Add");

        add_team.setText("Team");
        add_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_teamActionPerformed(evt);
            }
        });
        menu_add.add(add_team);

        add_player.setText("Player");
        add_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_playerActionPerformed(evt);
            }
        });
        menu_add.add(add_player);

        add_season.setText("Season");
        add_season.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_seasonActionPerformed(evt);
            }
        });
        menu_add.add(add_season);

        add_match.setText("Match");
        add_match.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_matchActionPerformed(evt);
            }
        });
        menu_add.add(add_match);

        jMenuBar1.add(menu_add);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public void setString(String string) {
        this.string = string;
    }

    private void add_teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_teamActionPerformed
        JFrame_AddTeam teamFrame = new JFrame_AddTeam(app);
        teamFrame.setLocationRelativeTo(null);
        teamFrame.setVisible(true);
    }//GEN-LAST:event_add_teamActionPerformed

    private void add_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_playerActionPerformed
        JFrame_AddPlayer playerFrame = new JFrame_AddPlayer(app);
        playerFrame.setLocationRelativeTo(null);
        playerFrame.setVisible(true);

    }//GEN-LAST:event_add_playerActionPerformed

    private void add_seasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_seasonActionPerformed
        JFrame_AddSeason seasonFrame = new JFrame_AddSeason(app);
        seasonFrame.setLocationRelativeTo(null);
        seasonFrame.setVisible(true);
    }//GEN-LAST:event_add_seasonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void edit_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_playerActionPerformed
        JFrame_EditPlayer editPlayer = new JFrame_EditPlayer(app);
        editPlayer.setLocationRelativeTo(null);
        editPlayer.setVisible(true);
    }//GEN-LAST:event_edit_playerActionPerformed

    private void edit_teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_teamActionPerformed
        JFrame_EditTeam editTeam = new JFrame_EditTeam(app);
        editTeam.setLocationRelativeTo(null);
        editTeam.setVisible(true);
        
    }//GEN-LAST:event_edit_teamActionPerformed

    private void edit_seasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_seasonActionPerformed
        JFrame_EditSeason editSeason = new JFrame_EditSeason(app);
        editSeason.setLocationRelativeTo(null);
        editSeason.setVisible(true);
        
    }//GEN-LAST:event_edit_seasonActionPerformed

    private void edit_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_countryActionPerformed
        JFrame_EditCountry editCountry = new JFrame_EditCountry(app);
        editCountry.setLocationRelativeTo(null);
        editCountry.setVisible(true);
    }//GEN-LAST:event_edit_countryActionPerformed

    private void export_seasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_seasonActionPerformed
        JFrame_ExportSeason exportSeason = new JFrame_ExportSeason(app);
        exportSeason.setLocationRelativeTo(null);
        exportSeason.setVisible(true);
    }//GEN-LAST:event_export_seasonActionPerformed

    private void export_teamActionPerformed(java.awt.event.ActionEvent evt) {
        JFrame_ExportTeam exportTeam = new JFrame_ExportTeam(app);
        exportTeam.setLocationRelativeTo(null);
        exportTeam.setVisible(true);
    }
    
    private void add_matchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_matchActionPerformed
        JFrame_AddMatch addMatch = new JFrame_AddMatch(app);
        addMatch.setLocationRelativeTo(null);
        addMatch.setVisible(true);
    }//GEN-LAST:event_add_matchActionPerformed

    private void export_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_playerActionPerformed
        JFrame_ExportPlayer exportPlayer = new JFrame_ExportPlayer(app);
        exportPlayer.setLocationRelativeTo(null);
        exportPlayer.setVisible(true);
    }//GEN-LAST:event_export_playerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add_match;
    private javax.swing.JMenuItem add_player;
    private javax.swing.JMenuItem add_season;
    private javax.swing.JMenuItem add_team;
    private javax.swing.JMenuItem edit_country;
    private javax.swing.JMenuItem edit_player;
    private javax.swing.JMenuItem edit_season;
    private javax.swing.JMenuItem edit_team;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu export;
    private javax.swing.JMenuItem export_player;
    private javax.swing.JMenuItem export_season;
    private javax.swing.JMenuItem export_team;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_add;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables
}
